import type { PrintDocumentKey } from "@/lib/print/customTemplate";

/**
 * Representative token values per document, keyed exactly like the
 * `templateData` object each *Printer.ts builds at real print time (see
 * lib/print/templateFields.ts for the curated token list). Used so the
 * builder canvas and its Print Preview show realistic values instead of raw
 * {{tokens}} while designing.
 */
const CLINIC_SAMPLE = {
  clinicName: "City Care Hospital",
  clinicAddress: "12 MG Road, Bengaluru",
  clinicPhone: "+91 98765 43210",
  clinicEmail: "care@citycarehospital.example",
  clinicWebsite: "www.citycarehospital.example",
  logoUrl: "",
};

export const SAMPLE_DATA: Record<PrintDocumentKey, Record<string, unknown>> = {
  opdReceipt: {
    ...CLINIC_SAMPLE,
    opdId: "OPDN0142",
    patientLabel: "Ananya Sharma (10234)",
    apptDate: "08/07/2026 10:30 AM",
    ageStr: "32 yr",
    patientGender: "Female",
    doctorLabel: "Dr. Rohan Mehta",
    applied: "₹800.00",
    disc: "₹50.00",
    taxAmt: "₹0.00",
    netAmt: "₹750.00",
    charges: [
      { name: "Consultation Fee", fee: "₹500.00" },
      { name: "Follow-up Fee", fee: "₹300.00" },
    ],
  },
  prescription: {
    ...CLINIC_SAMPLE,
    opdId: "OPDN0142",
    visitDate: "08/07/2026",
    patientName: "Ananya Sharma",
    uhid: "10234",
    ageStr: "32 Year",
    patientGender: "Female",
    patientAddress: "45 Park Street, Bengaluru",
    patientBloodGroup: "O+",
    patientAllergies: "Penicillin",
    doctorName: "Dr. Rohan Mehta",
    headerNote: "Follow up in 7 days",
    footerNote: "Take medicines after food",
    manualContent: "",
    medicines: [
      { name: "Paracetamol 500mg", dose: "1-0-1", doseInterval: "12 hrly", doseDuration: "5 days", instruction: "After food" },
      { name: "Amoxicillin 250mg", dose: "1-1-1", doseInterval: "8 hrly", doseDuration: "5 days", instruction: "After food" },
    ],
    findings: [{ category: "General", description: "Mild fever, throat congestion" }],
  },
  manualPrescription: {
    ...CLINIC_SAMPLE,
    opdId: "OPDN0142",
    visitDate: "08/07/2026",
    patientName: "Ananya Sharma",
    uhid: "10234",
    ageStr: "32 Year",
    patientGender: "Female",
    patientAddress: "45 Park Street, Bengaluru",
    patientBloodGroup: "O+",
    patientAllergies: "Penicillin",
    doctorName: "Dr. Rohan Mehta",
    headerNote: "Follow up in 7 days",
    footerNote: "Take medicines after food",
    manualContent: "Rx\n1. Tab. Paracetamol 500mg — 1-0-1 x 5 days",
    findings: [{ category: "General", description: "Mild fever, throat congestion" }],
  },
  pharmacyBill: {
    ...CLINIC_SAMPLE,
    billId: "PHARMAB1042",
    patientLabel: "Ananya Sharma (10234)",
    doctorName: "Dr. Rohan Mehta",
    caseId: "CASE-2201",
    prescriptionNo: "RX-8821",
    billDate: "08/07/2026",
    paymentMode: "Cash",
    totalAmount: "₹640.00",
    discountAmount: "₹20.00",
    taxAmount: "₹0.00",
    netAmount: "₹620.00",
    paidAmount: "₹620.00",
    balance: "₹0.00",
    lines: [
      { medicineName: "Paracetamol 500mg", batchNo: "B2201", expiryDate: "12/2027", quantity: 10, salePrice: "₹2.00", taxPercent: 0, discountPercent: 0, amount: "₹20.00" },
      { medicineName: "Amoxicillin 250mg", batchNo: "B2340", expiryDate: "05/2027", quantity: 15, salePrice: "₹6.00", taxPercent: 0, discountPercent: 0, amount: "₹90.00" },
    ],
  },
  ipdBill: {
    ...CLINIC_SAMPLE,
    ipdId: "IPDN0032",
    patientLabel: "Rakesh Verma (10567)",
    ageStr: "45 Year",
    patientGender: "Male",
    patientBloodGroup: "B+",
    patientPhone: "+91 91234 56789",
    doctorName: "Dr. Kavita Rao",
    doctorSpecialization: "Cardiology",
    admissionDate: "01/07/2026",
    dischargeDate: "06/07/2026",
    bedLabel: "204 – General Ward",
    caseNumber: "CASE-1980",
    totalCharges: "₹18,500.00",
    totalPaid: "₹18,500.00",
    balance: "₹0.00",
    paymentAmount: "₹5,000.00",
    paymentMode: "UPI",
    paymentNote: "Final settlement",
    paymentDate: "06/07/2026",
    paymentAddedByName: "Front Desk",
    charges: [
      { categoryName: "Room Rent", quantity: 5, unitPrice: "₹1,500.00", total: "₹7,500.00", date: "01/07/2026", note: "" },
      { categoryName: "Doctor Visit", quantity: 5, unitPrice: "₹500.00", total: "₹2,500.00", date: "01/07/2026", note: "" },
    ],
  },
  ipdDischargeSummary: {
    ...CLINIC_SAMPLE,
    ipdId: "IPDN0032",
    patientLabel: "Rakesh Verma (10567)",
    ageStr: "45 Year",
    patientGender: "Male",
    patientBloodGroup: "B+",
    bedDisplay: "204 – General Ward",
    caseNumber: "CASE-1980",
    admissionDate: "01/07/2026",
    dischargeDate: "06/07/2026",
    doctorName: "Dr. Kavita Rao",
    doctorSpecialization: "Cardiology",
    diagnosis: "Acute coronary syndrome",
    historyOfPresentIllness: "Chest pain for 2 days prior to admission",
    examinationFindings: "BP 130/85, pulse 88/min",
    investigations: "ECG, Troponin, Echo",
    treatmentGiven: "IV medications, monitoring",
    proceduresPerformed: "Angiography",
    conditionAtDischarge: "Stable",
    medicationsAtDischarge: "Aspirin 75mg OD, Atorvastatin 40mg OD",
    followUpInstructions: "Review after 2 weeks",
    additionalNotes: "Advised lifestyle changes",
    writtenByName: "Dr. Kavita Rao",
  },
  pathologyBill: {
    ...CLINIC_SAMPLE,
    billNo: "PATHB0921",
    patientLabel: "Ananya Sharma (10234)",
    referenceDoctor: "Dr. Rohan Mehta",
    caseId: "CASE-2201",
    paymentMode: "Cash",
    billDate: "08/07/2026",
    totalAmount: "₹1,200.00",
    discountAmount: "₹0.00",
    taxAmount: "₹0.00",
    netAmount: "₹1,200.00",
    paidAmount: "₹1,200.00",
    balance: "₹0.00",
    note: "",
    previousReportValue: "",
    items: [
      { testName: "Complete Blood Count", reportDate: "08/07/2026", charge: "₹500.00", tax: "—", amount: "₹500.00" },
      { testName: "Lipid Profile", reportDate: "08/07/2026", charge: "₹700.00", tax: "—", amount: "₹700.00" },
    ],
  },
  pathologyResults: {
    ...CLINIC_SAMPLE,
    billNo: "PATHB0921",
    billDate: "08/07/2026",
    reportDate: "09/07/2026",
    patientName: "Ananya Sharma",
    uhid: "10234",
    patientAge: "32",
    patientGender: "Female",
    referenceDoctor: "Dr. Rohan Mehta",
    reportedByName: "Lab Tech. Suresh",
    verifiedByName: "Dr. Pathologist Iyer",
    tests: [
      {
        testName: "Complete Blood Count",
        parameters: [
          { name: "Hemoglobin", value: "13.5", unit: "g/dL", referenceRange: "12-16", flag: "N" },
          { name: "WBC Count", value: "11200", unit: "/µL", referenceRange: "4000-11000", flag: "H" },
        ],
        remarks: "Mild leukocytosis",
      },
    ],
  },
  radiologyBill: {
    ...CLINIC_SAMPLE,
    billNo: "RADB0512",
    patientLabel: "Ananya Sharma (10234)",
    referenceDoctor: "Dr. Rohan Mehta",
    caseId: "CASE-2201",
    paymentMode: "Cash",
    billDate: "08/07/2026",
    totalAmount: "₹2,500.00",
    discountAmount: "₹0.00",
    taxAmount: "₹0.00",
    netAmount: "₹2,500.00",
    paidAmount: "₹2,500.00",
    balance: "₹0.00",
    note: "",
    previousReportValue: "",
    items: [{ testName: "Chest X-Ray", reportDate: "08/07/2026", charge: "₹2,500.00", tax: "—", amount: "₹2,500.00" }],
  },
  radiologyResults: {
    ...CLINIC_SAMPLE,
    billNo: "RADB0512",
    billDate: "08/07/2026",
    reportDate: "09/07/2026",
    patientName: "Ananya Sharma",
    uhid: "10234",
    patientAge: "32",
    patientGender: "Female",
    referenceDoctor: "Dr. Rohan Mehta",
    reportedByName: "Radiographer Singh",
    verifiedByName: "Dr. Radiologist Nair",
    tests: [
      {
        testName: "Chest X-Ray",
        findings: "No acute cardiopulmonary abnormality",
        impression: "Normal study",
      },
    ],
  },
};
