"use client";

import { useState, useEffect } from "react";
import { Plus, Printer, Eye, Wallet } from "lucide-react";
import { Button } from "@/components/ui/button";
import {
  Tooltip,
  TooltipContent,
  TooltipProvider,
  TooltipTrigger,
} from "@/components/ui/tooltip";
import { DataTable, type ColumnDef } from "@/components/ui/data-table";
import { TablePagination } from "@/components/common/TablePagination";
import { useApp, useDateFormatter, formatAmount } from "@/lib/context";
import { useApiQuery } from "@/lib/useApiQuery";
import { printPharmacyBillReceipt } from "@/components/pharmacy/PharmacyBillPrinter";
import { BillDetailsModal } from "./BillDetailsModal";
import { PaymentModal } from "./PaymentModal";
import type { PharmacyBill } from "./types";

function patientLabel(b: PharmacyBill) {
  if (!b.patientId) return "—";
  return `${b.patientId.name}${b.patientId.uhid ? ` (${b.patientId.uhid})` : ""}`;
}

function getBillColumns(
  handlers: {
    onView: (b: PharmacyBill) => void;
    onPay: (b: PharmacyBill) => void;
    onPrint: (b: PharmacyBill) => void;
  },
  symbol: string,
  currency: string | undefined,
  formatDateTime: (date: Date | string) => string,
): ColumnDef<PharmacyBill>[] {
  const fmt = (n: number) => formatAmount(n, currency);
  return [
    {
      key: "billNumber",
      header: "Bill No",
      sortable: true,
      sortValue: (b) => b.billNumber,
      skeletonWidth: "w-20",
      csvValue: (b) => `PHARMAB${b.billNumber}`,
      render: (b) => (
        <span className="text-xs font-medium text-primary-600 whitespace-nowrap">
          PHARMAB{b.billNumber}
        </span>
      ),
    },
    // {
    //   key: "caseId",
    //   header: "Case ID",
    //   skeletonWidth: "w-16",
    //   csvValue: (b) => b.caseId ?? "",
    //   render: (b) => (
    //     <span className="text-xs text-gray-600">{b.caseId ?? "—"}</span>
    //   ),
    // },
    {
      key: "createdAt",
      header: "Date",
      sortable: true,
      sortValue: (b) => new Date(b.createdAt),
      skeletonWidth: "w-32",
      csvValue: (b) => formatDateTime(b.createdAt),
      render: (b) => (
        <span className="text-xs whitespace-nowrap text-gray-600">
          {formatDateTime(b.createdAt)}
        </span>
      ),
    },
    {
      key: "patient",
      header: "Patient Name",
      sortable: true,
      sortValue: (b) => b.patientId?.name ?? "",
      skeletonWidth: "w-28",
      csvValue: patientLabel,
      render: (b) => (
        <span className="text-xs text-gray-800">{patientLabel(b)}</span>
      ),
    },
    {
      key: "generatedBy",
      header: "Generated By",
      skeletonWidth: "w-24",
      csvValue: (b) => b.createdBy?.name ?? "",
      render: (b) => (
        <span className="text-xs text-gray-600">
          {b.createdBy?.name ?? "—"}
        </span>
      ),
    },
    {
      key: "doctorName",
      header: "Doctor Name",
      skeletonWidth: "w-24",
      csvValue: (b) => b.doctorId?.name ?? b.doctorName ?? "",
      render: (b) => (
        <span className="text-xs text-gray-600">
          {b.doctorId?.name ?? b.doctorName ?? "—"}
        </span>
      ),
    },
    {
      key: "totalAmount",
      header: `Amount (${symbol})`,
      align: "right",
      sortable: true,
      sortValue: (b) => b.totalAmount,
      skeletonWidth: "w-16",
      csvValue: (b) => fmt(b.totalAmount),
      render: (b) => (
        <span className="text-xs text-gray-700">{fmt(b.totalAmount)}</span>
      ),
    },
    // {
    //   key: "discountAmount",
    //   header: `Discount (${symbol})`,
    //   align: "right",
    //   skeletonWidth: "w-20",
    //   csvValue: (b) => fmt(b.discountAmount),
    //   render: (b) => (
    //     <span className="text-xs text-gray-700">{`${fmt(b.discountAmount)} (${b.totalAmount > 0 ? fmt((b.discountAmount / b.totalAmount) * 100) : "0.00"}%)`}</span>
    //   ),
    // },
    // {
    //   key: "taxAmount",
    //   header: `Tax (${symbol})`,
    //   align: "right",
    //   skeletonWidth: "w-16",
    //   csvValue: (b) => fmt(b.taxAmount),
    //   render: (b) => (
    //     <span className="text-xs text-gray-700">{`${fmt(b.taxAmount)} (${b.totalAmount > 0 ? fmt((b.taxAmount / b.totalAmount) * 100) : "0.00"}%)`}</span>
    //   ),
    // },
    // {
    //   key: "netAmount",
    //   header: `Net Amount (${symbol})`,
    //   align: "right",
    //   sortable: true,
    //   sortValue: (b) => b.netAmount,
    //   skeletonWidth: "w-20",
    //   csvValue: (b) => fmt(b.netAmount),
    //   render: (b) => (
    //     <span className="text-xs font-medium text-gray-800">
    //       {fmt(b.netAmount)}
    //     </span>
    //   ),
    // },
    // {
    //   key: "paidAmount",
    //   header: `Paid (${symbol})`,
    //   align: "right",
    //   skeletonWidth: "w-16",
    //   csvValue: (b) => fmt(b.paidAmount),
    //   render: (b) => (
    //     <span className="text-xs text-gray-700">{fmt(b.paidAmount)}</span>
    //   ),
    // },
    // {
    //   key: "balance",
    //   header: `Balance (${symbol})`,
    //   align: "right",
    //   skeletonWidth: "w-16",
    //   csvValue: (b) => fmt(Math.max(0, b.netAmount - b.paidAmount)),
    //   render: (b) => {
    //     const bal = b.netAmount - b.paidAmount;
    //     return (
    //       <span
    //         className={`text-xs font-medium ${bal > 0 ? "text-danger-600" : "text-gray-700"}`}
    //       >
    //         {fmt(Math.max(0, bal))}
    //       </span>
    //     );
    //   },
    // },
    {
      key: "actions",
      header: "",
      align: "center",
      width: "w-28",
      skeletonWidth: "w-20",
      render: (b) => (
        <TooltipProvider delay={300}>
          <div className="flex items-center justify-center gap-1">
            <Tooltip>
              <TooltipTrigger
                onClick={(e) => {
                  e.stopPropagation();
                  handlers.onView(b);
                }}
                className="p-1.5 rounded hover:bg-gray-100 text-gray-500 hover:text-primary-600"
              >
                <Eye className="w-3.5 h-3.5" />
              </TooltipTrigger>
              <TooltipContent side="top">View</TooltipContent>
            </Tooltip>
            <Tooltip>
              <TooltipTrigger
                onClick={(e) => {
                  e.stopPropagation();
                  handlers.onPay(b);
                }}
                className="p-1.5 rounded hover:bg-gray-100 text-gray-500 hover:text-success-600"
              >
                <Wallet className="w-3.5 h-3.5" />
              </TooltipTrigger>
              <TooltipContent side="top">Add / View Payment</TooltipContent>
            </Tooltip>
            <Tooltip>
              <TooltipTrigger
                onClick={(e) => {
                  e.stopPropagation();
                  handlers.onPrint(b);
                }}
                className="p-1.5 rounded hover:bg-gray-100 text-gray-500 hover:text-gray-800"
              >
                <Printer className="w-3.5 h-3.5" />
              </TooltipTrigger>
              <TooltipContent side="top">Print</TooltipContent>
            </Tooltip>
          </div>
        </TooltipProvider>
      ),
    },
  ];
}

export function BillsList({
  onGenerateBill,
  refreshToken,
}: {
  onGenerateBill: () => void;
  refreshToken: number;
}) {
  const { tenant } = useApp();
  const { formatDateTime } = useDateFormatter();
  const [searchInput, setSearchInput] = useState("");
  const [search, setSearch] = useState("");
  const [page, setPage] = useState(1);
  const [viewingBill, setViewingBill] = useState<PharmacyBill | null>(null);
  const [payingBill, setPayingBill] = useState<PharmacyBill | null>(null);
  const limit = 100;

  useEffect(() => {
    const t = setTimeout(() => {
      setSearch(searchInput);
      setPage(1);
    }, 300);
    return () => clearTimeout(t);
  }, [searchInput]);

  const {
    data: billsData,
    isPending: loading,
    refetch: fetchBills,
  } = useApiQuery<{
    bills: PharmacyBill[];
    total: number;
    totalPages: number;
  }>(
    ["pharmacy-bills", search, page, refreshToken],
    `/api/dashboard/pharmacy/bills?search=${encodeURIComponent(search)}&page=${page}&limit=${limit}`,
    { keepPrevious: true },
  );
  const bills = billsData?.bills ?? [];
  const total = billsData?.total ?? 0;

  function printBill(b: PharmacyBill) {
    printPharmacyBillReceipt({
      billNumber: b.billNumber,
      billDate: formatDateTime(b.createdAt),
      caseId: b.caseId,
      prescriptionNo: b.prescriptionNo,
      patientName: b.patientId?.name,
      uhid: b.patientId?.uhid,
      doctorName: b.doctorId?.name ?? b.doctorName,
      lines: b.lines.map((l) => ({
        medicineName: l.medicineName,
        batchNo: l.batchNo,
        expiryDate: l.expiryDate,
        quantity: l.quantity,
        salePrice: l.salePrice,
        taxPercent: l.taxPercent,
        discountPercent: l.discountPercent,
        amount: l.amount,
      })),
      totalAmount: b.totalAmount,
      discountAmount: b.discountAmount,
      taxAmount: b.taxAmount,
      netAmount: b.netAmount,
      paidAmount: b.paidAmount,
      paymentMode: b.paymentMode,
      clinicName: tenant?.name ?? "Clinic",
      clinicAddress: tenant?.address || undefined,
      logoUrl: tenant?.logoUrl || undefined,
      printLayouts: tenant?.printLayouts,
      customPrintTemplates: tenant?.customPrintTemplates,
      currency: tenant?.currency,
      currencySymbol: tenant?.currencySymbol,
    });
  }

  const symbol = tenant?.currencySymbol || "₹";

  const billColumns = getBillColumns(
    {
      onView: setViewingBill,
      onPay: setPayingBill,
      onPrint: printBill,
    },
    symbol,
    tenant?.currency,
    formatDateTime,
  );

  return (
    <div className="flex flex-col h-full">
      <div className="flex items-center gap-2 px-4 pt-4 pb-3 border-b">
        <h1 className="text-lg font-semibold text-gray-800">Pharmacy Bill</h1>
        <div className="ml-auto flex items-center gap-2">
          <Button
            size="sm"
            onClick={onGenerateBill}
            className="bg-primary-600 hover:bg-primary-700 flex items-center gap-1.5"
          >
            <Plus className="w-4 h-4" /> Generate Bill
          </Button>
        </div>
      </div>

      <DataTable<PharmacyBill>
        columns={billColumns}
        data={bills}
        rowKey={(b) => b._id}
        loading={loading}
        skeletonRows={8}
        emptyText="No bills found"
        wrapperClassName="flex-1 overflow-auto"
        searchValue={searchInput}
        onSearchChange={setSearchInput}
        toolbarRight={
          <span className="text-xs text-gray-400">{total} records</span>
        }
        downloadable
        printable
        fileName="pharmacy-bills"
      />

      <TablePagination
        page={page}
        total={total}
        limit={limit}
        onPageChange={setPage}
        itemLabel="bills"
        className="shrink-0 rounded-none border-x-0 border-b-0"
      />

      <BillDetailsModal
        bill={viewingBill}
        onClose={() => setViewingBill(null)}
        onPay={() => {
          setPayingBill(viewingBill);
          setViewingBill(null);
        }}
      />
      <PaymentModal
        bill={payingBill}
        onClose={() => setPayingBill(null)}
        onSaved={fetchBills}
      />
    </div>
  );
}
